### ISSUE TITLE
Provide isRecentSearch usecase. I cant understand what it does.

### ISSUE THREAD

**Issue by ChaserVasya** [NazarenoCavazzon/flutter_paginated_list#3]

**Comment by NazarenoCavazzon** [comment]
I saw your comments. I'll get to them today 🫡.

**Comment by NazarenoCavazzon** [comment]
![image](https://github.com/NazarenoCavazzon/flutter_paginated_list/assets/49735945/808a3d62-db14-4172-abb5-a3c780e1b793)
